#!/bin/tcsh
#PBS -l walltime=1200
#PBS -l mem=4000MB
#PBS -l ncpus=32
#PBS -j oe
#PBS -q normal
#PBS -l wd

module load openmpi

limit stacksize unlimited

echo running with $PBS_NCPUS mpi ranks
time mpirun -np $PBS_NCPUS -report-bindings ./wrf.exe
