#!/bin/tcsh
#PBS -l walltime=3600
#PBS -l mem=4000MB
#PBS -l ncpus=2
#PBS -q express
#PBS -l wd
#PBS -l software=intel-cc/2:intel-fc/2

module load intel-cc
module load intel-fc
module load openmpi
module load netcdf/4.2.1.1
module load ncl/6.1.2

./compile
